"""modify length of usernames

Revision ID: 8c6ff08afcb1
Revises: ee24bbee24db
Create Date: 2018-01-21 12:40:41.230687

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8c6ff08afcb1'
down_revision = 'ee24bbee24db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'firstname',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('users', 'lastname',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=64),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('users', 'lastname',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('users', 'firstname',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###
